---
version: "3.2"

services:
  db:
    image: postgres
    env_file:
      - ./.env
    labels:
      com.datadog.ddhee2.description: "Database of record"
      com.datadog.ddhee2.type: "data provider"
    networks:
      - secured_enclave

  api:
    image: iamtonymayse:eehdd_api
    env_file:
      - ./.env
    labels:
      com.datadog.ddhee2.type: "micro service API"
      com.datadog.ddhee2.description: "user_web API"
    networks:
      - secured_enclave
      - sheltered_services
    depends_on:
      - db

  user_web:
    image: iamtonymayse:eehdd_web
    env_file:
      - ./.env
    labels:
      com.datadog.ddhee2.type: "user_web root app"
      com.datadog.ddhee2.description: "User-facing Web"
    networks:
      - dmz
      - sheltered_services
    depends_on:
      - api

  cache:
    image: iamtonymayse:eehdd_cache
    environment:
      - VARNISH_DOCKER_FILTER
    ports:
      - "8000:80"
    labels:
      com.datadog.ddhee2.type: "Primary Database"
      com.datadog.ddhee2.description: "user_web root app"
    networks:
      - dmz
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - api

  dd-agent:
    image: datadog/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup/:ro
    env_file:
      - ./.env
    environment:
      DD_APM_ENABLED: 0
      DD_PROCESS_AGENT_ENABLED: 0
      DD_KUBERNETES_NODE_LABELS_AS_TAGS: 0
    networks:
      - dd-agent
    depends_on:
      - cache

networks:
  secured_enclave:
  sheltered_services:
  dmz:
  dd-agent:
