---
version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    labels:
      com.datadog.ddhee2.description: "Database of record"
      com.datadog.ddhee2.type: "data provider"
    networks:
      - secured_enclave

  api:
    image: iamtonymayse:api_pip
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DD_API_KEY: ${DD_API_KEY}
    labels:
      com.datadog.ddhee2.type: "micro service API"
      com.datadog.ddhee2.description: "user_web API"
    networks:
      - secured_enclave
      - sheltered_services
    depends_on:
      - db

  user_web:
    image: iamtonymayse:eehdd_web
    labels:
      com.datadog.ddhee2.type: "user_web root app"
      com.datadog.ddhee2.description: "User-facing Web"
    networks:
      - dmz
      - sheltered_services
    depends_on:
      - api

  cache:
    image: iamtonymayse:eehdd_cache
    ports:
      - "8000:80"
    labels:
      com.datadog.ddhee2.type: "Primary Database"
      com.datadog.ddhee2.description: "user_web root app"
    networks:
      - dmz
    depends_on:
      - api

  dd-agent:
    image: datadog/agent
    environment:
      DD_API_KEY: ${DD_API_KEY}
      DD_APM_ENABLED: 0
      DD_PROCESS_AGENT_ENABLED: 0
      DD_KUBERNETES_NODE_LABELS_AS_TAGS: 0
    networks:
      - dd-agent
    depends_on:
      - cache

networks:
  secured_enclave:
  sheltered_services:
  dmz:
  dd-agent:
