FROM eeacms/varnish:latest

RUN \
  apt-get update \
  && apt-get -y install gettext-base apt-transport-https ca-certificates curl gnupg2 software-properties-common \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian jessie stable"
RUN apt-get update && apt-get install -y docker-ce

ENTRYPOINT /bin/sh
